### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by nordnomad** [readium/SDKLauncher-Android#124]
I am following instructions under this link https://docs.google.com/document/d/1ebFQ-8BGoiamKO4K0ZiL1nH6b8wulJ-ORyZKiDEYi-8/edit

Also I add this setting to local.properties
`readium.ndk_experimental=true
readium.ndk_clang=false
readium.ndk_skipARM=false
readium.ndk_skipX86=false`

I am getting the following error

`Information:Gradle tasks [:app:generateArmDebugSources, :app:generateArmDebugAndroidTestSources, :app:prepareArmDebugUnitTestDependencies, :app:mockableAndroidJar, :app:compileArmDebugSources, :app:compileArmDebugAndroidTestSources, :app:compileArmDebugUnitTestSources, :lcp:generateArm7DebugSources, :lcp:prepareArm7DebugUnitTestDependencies, :lcp:mockableAndroidJar, :lcp:generateArm7DebugAndroidTestSources, :lcp:compileArm7DebugSources, :lcp:compileArm7DebugUnitTestSources, :lcp:compileArm7DebugAndroidTestSources]
Error:error: 'C:/SDKLauncher-Android/readium-sdk/Platform/Android/epub3/libs/armeabi-v7a/libepub3.so', needed by '../../../../build/intermediates/cmake/arm7/debug/obj/armeabi-v7a/liblcp.so', missing and no known rule to make it
Information:BUILD FAILED
Information:Total time: 7.042 secs
Information:1 error
Information:0 warnings
Information:See complete output in console`

Could you help me ? Thank's

**Comment by danielweck** [comment]
Because you are using the `feature/lcp` branch and `readium-lcp-client` which has a revised Gradle / CMake build system, you need to build the ReadiumSDK library separately (so that its independent reference from the LCP lib can be resolved adequately). See the additional `local.properties` configuration (`readium.sdk_lib_dir` and `readium.sdk_include_dir`), as per the README:

https://github.com/readium/readium-lcp-client/blob/develop/platform/android/README.md

https://github.com/readium/readium-lcp-client/blob/cd65c5e5615828c41aded659a9d518059149c1f9/platform/android/build.gradle#L25-L35

(note: the LCP lib can also be built without the ReadiumSDK, in cases where app developers only want to use a minimal version of the library without dependencies on the Readium engine)

You should be able to build the ReadiumSDK directly from its Gradle script (command line or Android Studio):å

https://github.com/readium/readium-sdk/blob/develop/Platform/Android/build.gradle

CC @clebeaupin @llemeurfr

**Comment by nordnomad** [comment]
Thank you @danielweck, your answer was helpful. I checked out develop branches for readium-lcp-client and redium-sdk, also I set addition properties that you adviced and was able to build this two projects.

But the problem with build of SDKLauncher-Android was still actual, I found the workaround - create necessary directory manualy and put there libepub3.so. With such solution gradle build passed. 

Now I see FilePickerActivity with directory '/storage/emulated/0/epubtest' that looks empty instead of I put there two files - one *.epub and *.lcpl Then I click Ok button and app crashes with the following stacktrace

`09-12 12:26:56.156 7660-7660/org.readium.sdk.android.launcher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: org.readium.sdk.android.launcher, PID: 7660
                                                                                java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/org.readium.sdk.android.launcher-2/lib/arm/libepub3.so"...
                                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                    at java.lang.System.loadLibrary(System.java:1076)
                                                                                    at org.readium.sdk.android.EPub3.<clinit>(EPub3.java:44)
                                                                                    at org.readium.sdk.android.launcher.ContainerList.onCreate(ContainerList.java:252)
                                                                                    at android.app.Activity.performCreate(Activity.java:6251)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by danielweck** [comment]
note that the "launcher app" is really just a tech demo / integration examplar, so the FilePickerActivity is a quick and dirty UI to allow the user to choose a source folder on the device's internal storage (by default "epubtest").

**Comment by danielweck** [comment]
what is your ndk version?

**Comment by nordnomad** [comment]
Android v6.0.1 
NDK 15.2.4203891

It is very similar to this issue https://github.com/android-ndk/ndk/issues/126

I've checked the app on android 7.0 and it works

**Comment by danielweck** [comment]
could you please try NDK 14 (GCC, we don't support Clang yet)

**Comment by nordnomad** [comment]
A lot of thanks @danielweck, will try it later, and provide you results, as now app is working with android v7

Now I am getting this toast when try to open lcpl file `LCP EPUB license failed to initiate.` 
I suggest this is issut with root cetrificate and jks. Can you advice with this issue? And what is the connection between this certificate and the one on the lcp-server?

**Comment by danielweck** [comment]
LCP server `10013` is with the certificate for "basic profile", which is the default one shipped with the launcher apps:

https://github.com/readium/SDKLauncher-OSX/blob/feature/lcp/Resources/LCP%20Root%20Certificate.crt

https://github.com/readium/SDKLauncher-iOS/blob/feature/lcp/Resources/LCP%20Root%20Certificate.crt

https://github.com/readium/SDKLauncher-Android/blob/feature/lcp/SDKLauncher-Android/app/src/main/assets/lcp/lcp.crt

**Comment by danielweck** [comment]
LCP server `11013` is the "1.0 Profile". Please ask @llemeurfr :)

**Comment by nordnomad** [comment]
`A ContentFilter object that supports byte ranges should only make RangeFilterContext objects. `

What can be the reason of this exception and how it can be fixed?

**Comment by nordnomad** [comment]
@danielweck I just checked your suggestion about ndk14 and now app is works perfectly without any issues on android v6

Thank you a lot!

**Comment by llemeurfr** [comment]
please contact EDRLab to have access to an LCP test server + exchange about your use case.

**Comment by danielweck** [comment]
New issue about NDK 14 vs. 15
https://github.com/readium/SDKLauncher-Android/issues/125
Thank you!!

**Comment by danielweck** [comment]
Possibly-related to NDK v14 vs. v15: https://github.com/readium/readium-lcp-client/issues/42
