### ISSUE TITLE
Can anyone help me In this error Readium Launcher Error

### ISSUE THREAD

**Issue by ashishdixitmca** [readium/SDKLauncher-Android#89]
FATAL EXCEPTION: main
                                                                                Process: org.readium.sdk.android.launcher, PID: 1319
                                                                                java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.readium.sdk.android.launcher-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libepub3.so"
                                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                    at java.lang.System.loadLibrary(System.java:989)
                                                                                    at org.readium.sdk.android.EPub3.<clinit>(EPub3.java:44)
                                                                                    at org.readium.sdk.android.launcher.ContainerList.onCreate(ContainerList.java:135)
                                                                                    at android.app.Activity.performCreate(Activity.java:6221)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:172)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5832)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
c

**Comment by ashishdixitmca** [comment]
Please anyone suggest me how to solve this issue

**Comment by rkwright** [comment]
Can you provide a little more info? Did you clone master or develop?  

Be aware that we are about to push a major change as we are switching from Eclipse to Android Studio.  This should happen in the next day or so.

**Comment by rkwright** [comment]
@ashishdixitmca   We have now switched to Android Studio.  Can you clone develop and try it with Android Studio 2.1?
