### ISSUE TITLE
need help to execute SDKLauncher-Android

### ISSUE THREAD

**Issue by ashishdixitmca** [readium/SDKLauncher-Android#94]
Hi Can you help me in this i m trying to execute sdk Launcher but i m geeting below error. It would be great if anyone can help me in this issue. Thanks

 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: org.readium.sdk.android.launcher, PID: 8464
                                                                                java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.readium.sdk.android.launcher-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libepub3.so"
                                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                    at java.lang.System.loadLibrary(System.java:989)
                                                                                    at org.readium.sdk.android.EPub3.<clinit>(EPub3.java:44)
                                                                                    at org.readium.sdk.android.launcher.ContainerList.onCreate(ContainerList.java:135)
                                                                                    at android.app.Activity.performCreate(Activity.java:6221)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:172)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5832)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

NOTE:---------------------------
Set up 
OS--Windows8.1
Android Studio1.5
Jdk1.8
Downloaded NDK  -android-ndk-r10e

Thanks

**Comment by ashishdixitmca** [comment]
when i m building from ndk-buid command i m getting this error 

C:\Users\ashish.dixit\Desktop\Redium\readium-sdk\Platform\Android\jni>C:\Users\ashish.dixit\android-ndk-r10e\ndk-build
Android NDK: WARNING: APP_PLATFORM android-19 is larger than android:minSdkVersion 11 in C:/Users/ashish.dixit/Desktop/Redium/readium-sdk/Platform/Android/AndroidManifest.xml
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: C:/Users/ashish.dixit/Desktop/Redium/readium-sdk/Platform/Android/jni/Android.mk
C:/Users/ashish.dixit/android-ndk-r10e/build/core/add-application.mk:199: *** Android NDK: Aborting...    .  Stop.

The project i have downloded from link :-https://github.com/readium/SDKLauncher-Android
Thanks

**Comment by ashishdixitmca** [comment]
In eclipse also i tried i m getting below error

"C:\\Users\\ashish.dixit\\android-ndk-r10e\\ndk-build.cmd" -C . V=1 NDK_APPLICATION_MK=Application.mk "NDK_PROJECT_PATH=C:\\Users\\ashish.dixit\\Desktop\\Redium\\readium-sdk\\Platform\\Android" APP_BUILD_SCRIPT=Android.mk NDK_DEBUG=1 all 
Android NDK: WARNING: APP_PLATFORM android-21 is larger than android:minSdkVersion 11 in C:\Users\ashish.dixit\Desktop\Redium\readium-sdk\Platform\Android/AndroidManifest.xml    
Android NDK: ERROR:Android.mk:icuuc: LOCAL_SRC_FILES points to a missing file    
C:/Users/ashish.dixit/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
Android NDK: Check that ./../../ePub3/ThirdParty/icu4c/lib/armeabi-v7a/libicuuc.a exists  or that its path is correct   
make.exe: Entering directory `C:/Users/ashish.dixit/Desktop/Redium/readium-sdk/Platform/Android'
make.exe: Leaving directory `C:/Users/ashish.dixit/Desktop/Redium/readium-sdk/Platform/Android'

**Comment by danielweck** [comment]
You need to checkout the repository and its submodules on the develop branch. Eclipse has been deprecated, Google now recommends Android Studio and the Grade build system. Compiling / debugging from Windows is now as easy as OSX, Linux.

**Comment by ashishdixitmca** [comment]
Thanks @danielweck 

I tried with android studio also 

Hi Can you help me in this i m trying to execute sdk Launcher but i m geeting below error. It would be great if anyone can help me in this issue. Thanks

E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.readium.sdk.android.launcher, PID: 8464
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.readium.sdk.android.launcher-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libepub3.so"
at java.lang.Runtime.loadLibrary(Runtime.java:366)
at java.lang.System.loadLibrary(System.java:989)
at org.readium.sdk.android.EPub3.(EPub3.java:44)
at org.readium.sdk.android.launcher.ContainerList.onCreate(ContainerList.java:135)
at android.app.Activity.performCreate(Activity.java:6221)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5832)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

NOTE:---------------------------
Set up 
OS--Windows8.1
Android Studio1.5
Jdk1.8
Downloaded NDK -android-ndk-r10e

Thanks

**Comment by danielweck** [comment]
please update Android Studio and NDK to the latest versions.

**Comment by ashishdixitmca** [comment]
thanks for your reply 

currently i am facing below error i have code taken from develop branch

Error:Could not determine the dependencies of task ':app:compileDebugAidl'.
> Task with path ':epub3:buildMk' not found in project ':app'.

**Comment by danielweck** [comment]
Is that with the latest version of Android Studio?

**Comment by ashishdixitmca** [comment]
Hi @danielweck 
Yes as you suggest i m using Android2.1 and latest ndk version while building getting the below error

Information:Gradle tasks [:app:clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:prepareDebugUnitTestDependencies, :app:mockableAndroidJar, :app:assembleDebug]
Build Js Assets
1464249170251
26 May 2016 07:52:50 GMT
Error:Could not determine the dependencies of task ':app:compileDebugAidl'.
> Task with path ':epub3:buildMk' not found in project ':app'.
Information:BUILD FAILED
--------------------------------------------------------------------------------------------------------
from another branch also i have tried It is building sucessfull showing book in app while clicking then i m getting below error:

FATAL EXCEPTION: main
                                                                              Process: org.readium.sdk.android.launcher, PID: 896
                                                                              java.lang.UnsatisfiedLinkError: No implementation found for org.readium.sdk.android.Container org.readium.sdk.android.EPub3.openBook(java.lang.String) (tried Java_org_readium_sdk_android_EPub3_openBook and Java_org_readium_sdk_android_EPub3_openBook__Ljava_lang_String_2)
                                                                                  at org.readium.sdk.android.EPub3.openBook(Native Method)
                                                                                  at org.readium.sdk.android.launcher.ContainerList$1.onItemClick(ContainerList.java:112)
                                                                                  at android.widget.AdapterView.performItemClick(AdapterView.java:334)
                                                                                  at android.widget.AbsListView.performItemClick(AbsListView.java:1544)
                                                                                  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3686)
                                                                                  at android.widget.AbsListView$3.run(AbsListView.java:5600)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:145)

**Comment by danielweck** [comment]
what are the contents of the readium-sdk folder (submodule)?
is this repository fully synched with the develop branch?

**Comment by ashishdixitmca** [comment]
Steps :- I have Clone from develop then in develop folder there are folder like redium- skd and readium js both was empty initial so i downloaded redium-sdk  and redium-js then copied content to both folder in sdk and js folder. in redium sdk  i have only copied Android/platform folder 
did i done anything thin wrong ?

**Comment by danielweck** [comment]
you must initialise and update the submodule repositories correctly. 

In a nutshell:

git submodule init
git submodule update
git checkout develop

You can follow the same instructions as: https://github.com/readium/readium-js-viewer/blob/develop/README.md#git-initialisation

**Comment by ashishdixitmca** [comment]
We are using Windows OS and android studio  2.1. not sure about the nutshell. if you could provide  guidance for windows as well as for android studio  2.1 settings that will be very helpful for us to get the running source code for Android application .

**Comment by danielweck** [comment]
is git installed on your machine? you can use gitbash to run the shell commands I mentioned above, or you can use the github app.
once your copy of the source tree is ready, then let's talk about compiling.

**Comment by ashishdixitmca** [comment]
ok thanks a lot  I will go the same

**Comment by ashishdixitmca** [comment]
hi @danielweck   thanks for your quick reply i followed the steps as you as told now it is showing branch is upto date with origin.develop and currently i m in develop branch now please guide the next step

**Comment by danielweck** [comment]
now do the same with SDKLauncher-Android - readium-sdk - readium-shared-js 
then open the project with Android Studio, inside the SDKLauncher-Android/SDKLauncher-Android/ folder (yes, twice the same name!)

**Comment by ashishdixitmca** [comment]
means whatever code now i clone i need to copy in respective folder right? 
then need to import ?

**Comment by danielweck** [comment]
I showed you the steps for readium-js-viewer because they are similar to any other Readium repository (like SDKLauncher-Android).
You do not need to copy anything. Just checkout the GitHub source tree (including submodules) and open the project from Android Studio..

**Comment by ashishdixitmca** [comment]
Hi @danielweck  I m not able to execute still same isssue i m facing till now i done R&D

Step-1 From git clone the complete source tree for readium-js-viewer  
Checkout the develop branch.
Under  android launcher Application readium-sdk folder and radium-js folder replaced above readium-js-view content .
Open in android studio as launcher android Application  while building getting below error
Information:Gradle tasks [:app:generateDebugSources, :app:prepareDebugUnitTestDependencies, :app:mockableAndroidJar, :app:generateDebugAndroidTestSources]
Build Js Assets
1464268548789
26 May 2016 13:15:48 GMT
Error:Could not determine the dependencies of task ':app:compileDebugAidl'.
> Task with path ':epub3:buildMk' not found in project ':app'.
Note I m opening readium-js-viewer directly there will not be any android gradle project .
-----------------------------------------------------------------------------------------------------------------------------
Step-2
Clone the launcher Android    checkout develop
Imported to android studio same error is coming
Information:Gradle tasks [:app:generateDebugSources, :app:prepareDebugUnitTestDependencies, :app:mockableAndroidJar, :app:generateDebugAndroidTestSources]
Build Js Assets
1464268548789
26 May 2016 13:15:48 GMT
Error:Could not determine the dependencies of task ':app:compileDebugAidl'.
> Task with path ':epub3:buildMk' not found in project ':app'.

**Comment by danielweck** [comment]
As I said above, please do not copy files manually.

You have to checkout the develop branch of SDKLauncher-Android (as the root repository), not readium-js-viewer (I only gave you this example for git command line instructions).

Then, inside the SDKLauncher-Android folder there are the readium-shared-js and readium-sdk submodules, which you also have to synchronise with the develop branch.

I suggest you read some documentation about git, as you will need to update your clone/fork regularly.

I hope this helps.

**Comment by ashishdixitmca** [comment]
@danielweck  Hi Still getting same error  really sorry for asking many times now as per git doc in gitbash i configured username email n all then I  cloned Launcher Android /submodule init/submodule  update/ git checkout develop .now i m in develop \and open in studio  getting same error 
After that i tried also 
Approach 2; while taking git pull -rebase its showing no correct right access.? 
Approach 3: And as per this url https://github.com/readium/SDKLauncher-Android i tried to compile also MakeHeader.sh not found bad interpreter it is showing 
can you please tell me where i m wrong ?

**Comment by ashishdixitmca** [comment]
HI @danielweck  I think now its sync but now i m getting below error:

Error:FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\ashish.dixit\Documents\GitHub\Ashish2\Launcher-Android\SDKLauncher-Android\app\build_epubReadingSystem.gradle' line: 157

* What went wrong:
Execution failed for task ':app:buildEpubReadingSystem'.
> Could not copy file 'C:\Users\ashish.dixit\Documents\GitHub\Ashish2\Launcher-Android\SDKLauncher-Android\app\src\main\assets\readium-shared-js\epubReadingSystem_EMPTY.js' to 'C:\Users\ashish.dixit\Documents\GitHub\Ashish2\Launcher-Android\SDKLauncher-Android\app\src\main\assets\readium-shared-js\epubReadingSystem.js'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ashishdixitmca** [comment]
@danielweck   Hi Now it is running in my mobile really thanks for your kind support without support it was not possible for me

**Comment by danielweck** [comment]
`libepub3.so` is the output from the `readium-sdk` build.
Have you tried this?
`cd SDKLauncher-Android/readium-sdk/Platform/Android && ./gradlew build`

**Comment by adnanali-indpro** [comment]
yes i have tried but its not working. libepub3.so is 32 bit need 64 bit error i am getting
